### ISSUE TITLE
lokinet gui should not minimize to tray by default

### ISSUE THREAD

**Issue by majestrate** [oxen-io/lokinet-gui#35]
see https://github.com/oxen-io/lokinet/issues/2075

**Comment by jagerman** [comment]
Disagree.  Closing to taskbar is the norm for service-type applications on Windows.  On my Windows system PIA, Steam, software for monitoring my UPS, drivers, and other background services all do exactly this.

**Comment by majestrate** [comment]
just because windows does it, doesn't mean users like it.

**Comment by jagerman** [comment]
Some users will dislike *any* behaviour.  If you force the window to always be active whenever lokinet is active you will *also* have users who dislike it and file bug reports about it.

**Comment by majestrate** [comment]
fair
