### ISSUE TITLE
Ded?

### ISSUE THREAD

**Issue by necro-nemesis** [oxen-io/lokinet-gui#9]
Are you going in another direction with the GUI?

**Comment by majestrate** [comment]
not dead. work just needs to be resumed

**Comment by necro-nemesis** [comment]
So not dead. Was the work farmed out?

**Comment by majestrate** [comment]
gui hooked into ci with build artifacts bring dropped [here](https://oxen.rocks/oxen-io/lokinet-gui/)

i am not doing dev on the gui bits, i believe that @Bilb is tasked with that.
